name: Run merge tests
run-name: Run merge tests for PR ${{ github.event.client_payload.number }} by @${{ github.event.client_payload.owner }}
on:
  repository_dispatch:
    types: [merged_pull_request]

jobs:
  Run-Local-Tests:
    runs-on: self-hosted
    steps:
      - name: Check out obscuro-test
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test

      - name: Check out go-obscuro code
        uses: actions/checkout@v3
        with:
          repository: obscuronet/go-obscuro
          path: ./go-obscuro

      - name: Docker clean containers and images
        run: |
          for i in `docker ps -a | awk '{ print $1 } ' | grep -v CONTAINER`; do docker stop $i && docker rm $i; done
          docker system prune -af

      - name: Build wallet_extension
        run: |
          cd ${{ github.workspace }}/go-obscuro/tools/walletextension/main
          go build -o ${{ github.workspace }}/obscuro-test/artifacts/wallet_extension
          ls -l ${{ github.workspace }}/obscuro-test/artifacts   

      - name: Build docker containers
        run: |
          cd ${{ github.workspace }}/obscuro-test/utils/testnet
          docker compose -f docker-compose.local.yml build --parallel 

      - name: Start up testnet
        run: |
          cd ${{ github.workspace }}/go-obscuro/testnet
          ./testnet-local-gethnetwork.sh --pkaddresses=0x13E23Ca74DE0206C56ebaE8D51b5622EFF1E9944,0x0654D8B60033144D567f25bF41baC1FB0D60F23B
          ./testnet-deploy-contracts.sh --l1host=gethnetwork --pkstring=f52e5418e349dccdda29b6ac8b0abe6576bb7713886aa85abea6181ba731f9bb
          ./start-obscuro-node.sh --sgx_enabled=true --l1host=gethnetwork --mgmtcontractaddr=0xeDa66Cc53bd2f26896f6Ba6b736B1Ca325DE04eF --hocerc20addr=0xC0370e0b5C1A41D447BDdA655079A1B977C71aA9 --pocerc20addr=0x51D43a3Ca257584E770B6188232b199E76B022A2 --is_genesis=true --node_type=sequencer 
          ./testnet-deploy-l2-contracts.sh --l2host=testnet-host-1

      - name: Capture container logs
        run: |
          cd ${{ github.workspace }}/go-obscuro/testnet
          docker logs -f `docker ps -aqf "name=testnet-host-1"` > testnet-host-1.out &
          docker logs -f `docker ps -aqf "name=testnet-enclave-1"` > testnet-enclave-1.out &

      - name: Run allocations
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -m obscuro.local fund_layer_one
          /usr/local/bin/pysys.py run -m obscuro.local fund_layer_two
          /usr/local/bin/pysys.py run -m obscuro.local fund_test_users

      - name: Run tests
        run: |
          cd ${{ github.workspace }}/obscuro-test/tests
          /usr/local/bin/pysys.py run -m obscuro.local -e skip -e robustness

      - name: Discord notification
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.CONT_INT_WEBHOOK }}
          title: "Merge tests for PR ${{ github.event.client_payload.number }} by @${{ github.event.client_payload.owner }}"
          description: "Local testnet tests on PR merge"
          avatar_url: ${{ secrets.AVATAR_URL }}

      - name: Upload testcase output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/obscuro-test/**/Output
          retention-days: 2

      - name: Upload container logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: container-artifact
          path: |
            ${{ github.workspace }}/go-obscuro/testnet/*.out
          retention-days: 2